### ISSUE TITLE
Fix ball bouncing bug

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Pong-in-JS#1]
The ball can be seen bouncing off when it's close to the bats even when it doesn't appear to touch the bat.

**Comment by mhamzanadeem** [comment]
I am participating in hacktoberfest .  can u assign me this issue

**Comment by mhamzanadeem** [comment]
> The ball can be seen bouncing off when it's close to the bats even when it doesn't appear to touch the bat.

I played the game  , I didnt feel any issue in bouncing of ball .Can u further elaborate this issue  ?

**Comment by swagatmitra-b** [comment]
https://github.com/swagatmitra-b/Pong-in-JS/assets/116569056/829017bd-f230-42e1-abc3-18c1ac5bb380

**Comment by mhamzanadeem** [comment]
ok .
