### ISSUE TITLE
Implement a scorecard

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Pong-in-JS#2]
Currently, the game only supports a one-miss-one-win style where the opposite player wins if our player misses the ball once. Instead, try to implement a score table where on each miss, the scores are updated and the game continues till a player has a score of 10.

**Comment by mhamzanadeem** [comment]
I am participating in hacktoberfest . can u assign this feature to me

**Comment by mhamzanadeem** [comment]
can u tell me by which key  the game will start .  I am pressing "P" but game is not starting. Can u guide  me about controls

**Comment by bhavy03** [comment]
hey @swagatmitra-b would you please assign this issue to me

**Comment by mhamzanadeem** [comment]
can anyone tell , by pressing which button , the game will start

**Comment by swagatmitra-b** [comment]
You can play by pressing the "P" key on your keyboard. Please note that "P" in this case is just the key and does not denote the case of the letter. Make sure your Caps Lock is not on.

**Comment by mhamzanadeem** [comment]
> You can play by pressing the "P" key on your keyboard. Please note that "P" in this case is just the key and does not denote the case of the letter. Make sure your Caps Lock is not on.

On this interface , i am pressing "P" ( Caps lock is not on) .  but game is not starting.  Can u  tell me what mistake i am doing ? 
![999](https://github.com/swagatmitra-b/Pong-in-JS/assets/114602354/f6e7871e-4318-4471-b005-9f9ae55abe51)

**Comment by swagatmitra-b** [comment]
![Screenshot1](https://github.com/swagatmitra-b/Pong-in-JS/assets/116569056/9ead5b1f-a337-48cd-9853-62d84ad1f1b7)
Your screen should appear something like this. I'm not sure why it isn't in your machine but it's probably because of viewport misalignments. You could try tweaking with the CSS and see if it resolves.

**Comment by mhamzanadeem** [comment]
> ![Screenshot1](https://user-images.githubusercontent.com/116569056/271776301-9ead5b1f-a337-48cd-9853-62d84ad1f1b7.png) Your screen should appear something like this. I'm not sure why it isn't in your machine but it's probably because of viewport misalignments. You could try tweaking with the CSS and see if it resolves.

i am getting this issue on inspect .  Can u help me out ? 
![111111](https://github.com/swagatmitra-b/Pong-in-JS/assets/114602354/864c377c-8ea2-49a3-9fee-061a03ac47fd)

**Comment by mhamzanadeem** [comment]
Thank God .  it has been run

**Comment by swagatmitra-b** [comment]
Please leave a comment describing how you resolved the CORS error so that other contributors can refer to it

**Comment by mhamzanadeem** [comment]
> Please leave a comment describing how you resolved the CORS error so that other contributors can refer to it

Problem :
I was opening the " index.html " file directly by clicking on it .  that was causing the error . 

Solution:
The solution was that :
1 . Open the folder "Pong-in-JS"  in Visual studio code (Or open in favourite IDE you are using).  Then install extension Live server (only available in Vs code ) , Then right click on "index.html" and you will see the option "Open with Live server " , click on it

**Comment by mhamzanadeem** [comment]
> Currently, the game only supports a one-miss-one-win style where the opposite player wins if our player misses the ball once. Instead, try to implement a score table where on each miss, the scores are updated and the game continues till a player has a score of 10.

should we make a separate "score.js" file or should we write code in "index.js"

**Comment by mhamzanadeem** [comment]
> > Currently, the game only supports a one-miss-one-win style where the opposite player wins if our player misses the ball once. Instead, try to implement a score table where on each miss, the scores are updated and the game continues till a player has a score of 10.
> 
> should we make a separate "score.js" file or should we write code in "index.js"

@swagatmitra-b   plz guide me on this problem

**Comment by swagatmitra-b** [comment]
I'm sorry to inform you that due to some unforeseen circumstances, I will not be able to maintain this repo for hacktoberfest anymore. I appreciate your earnest contributions and wish you the best in your career. Good luck.
